# Generated by Django 3.1.2 on 2020-11-02 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('article_like', models.IntegerField(verbose_name='赞同数')),
                ('content', models.TextField(max_length=10000)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Article_Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.SmallIntegerField()),
                ('tag_id', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'article_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.PositiveSmallIntegerField()),
                ('tag_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
